import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { SocialIcon } from "react-social-icons";
import { AlbumList } from "../components/album/album-list/album-list";
import { supabase } from "../utils/supabaseClient";
import PageLayout from "../components/layout/page-layout";

/*export async function getServerSideProps() {
	const { data, error } = await supabase
		.from("albums")
		.select(`*, artists (name)`)
		.order("id", { ascending: false });

	console.log("get static props: ", data);

	return {
		props: {
			data,
		},
	};
}*/

const Home: NextPage = ({ data }: any) => {
	return (
		<>
			<Head>
				<title>feel de agua</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<PageLayout>
				<main className="flex flex-col justify-center items-center">
					<AlbumList></AlbumList>
				</main>

				<footer className="flex flex-col justify-center items-center pb-10">
					<div className="flex flex-row justify-center items-center">
						<SocialIcon
							className="ml-4"
							bgColor="white"
							fgColor="black"
							target={"_blank"}
							url="https://www.instagram.com/feeldeagua"></SocialIcon>
						<SocialIcon
							className="ml-4"
							bgColor="white"
							fgColor="black"
							target={"_blank"}
							url="https://www.youtube.com/user/feeldeagua"></SocialIcon>
						<SocialIcon
							className="ml-4"
							bgColor="white"
							fgColor="black"
							target={"_blank"}
							url="https://www.facebook.com/feeldeagua/"></SocialIcon>
					</div>

					<span className="mt-8 ml-4">feel de agua</span>
					<span className="mt-1 ml-4">2022</span>
				</footer>
			</PageLayout>
		</>
	);
};

export default Home
