import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { AlbumList } from "../components/album/album-list/album-list";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>feel de agua</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="flex flex-col justify-center items-center mt-10">
					<picture>
						<img
							src="/logo-feel-redondo-blanco4.png"
							alt="logo feel"
							width={100}
							height={100}
						/>
					</picture>
					<h1 className="font-bold text-xl mt-4 mb-12">Discos</h1>
				</div>
				<AlbumList></AlbumList>
			</main>

			<footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Powered by{" "}
				</a>
			</footer>
		</div>
	);
};

export default Home
